### PR TITLE
[WIP] Add image layout transitions

### PR DESCRIPTION
**Pull request by aschrein**
Hi,

Cool project.
Currently image layout transitions are not correct which prevents any examples from working on my machine(NV 1070). Here's a sketch of how it might look like for 2d images. It's not ideal but at least it makes examples work for me. For simple use case it's enough to track the image layout in one variable which I'm doing.

Thanks

### CODE REVIEW

**Comment by fynv** [comment]
Hi Anton, 
About ' prevents any examples from working on my machine(NV 1070)', I wonder what the error looks like exactly. 
The code worked for me on RTX 2060 super, execpt for an unrelated validation warning. 

I was not quite sure if I really need to track the image layout, because the spec says:

_If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define a image layout transition, oldLayout must be **VK_IMAGE_LAYOUT_UNDEFINED or** the current layout of the image subresources affected by the barrier_

Thanks for the sketch. I guess I won't merge it directly, because I'm also applying barriers for SSBO buffers (Not sure if these are neccessary at all). But if a fix is needed, I want to keep the two cases aligned.

**Comment by fynv** [comment]
Seems I missed the layout transition for attachments. Just added them. If that was the problem, the last commit might have fixed it.

**Comment by fynv** [comment]
After some more reading, I see that this is still not quite right.. The whole picture looks like I need to keep tracking not only the current image layout, but also the current access mask.. The latter also applies to SSBO buffers. Reworking the code now.

**Comment by aschrein** [comment]
The strange thing is that I didn't receive any validation errors either. Also IIRC on NV image layouts are no-ops. Strange. Anyways, thanks for the update! gonna check that last commit out.

**Comment by aschrein** [comment]
The current patch still doesn't make any examples work. Something is missing.

**Comment by aschrein** [comment]
Even this doesn't work(black image):
```python
import VkInline as vki
import numpy as np
from PIL import Image

image_in =  np.array(Image.open('fei.png').convert('RGBA'))

VK_FORMAT_R8G8B8A8_SRGB = 43

width = image_in.shape[1]
height =  image_in.shape[0]

tex2d = vki.Texture2D(width, height, VK_FORMAT_R8G8B8A8_SRGB)
tex2d.upload(image_in)

image_out = np.empty((height, width, 4), dtype=np.uint8)
tex2d.download(image_out)

Image.fromarray(image_out, 'RGBA').save('output.png')
```
I think transition to VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL is of necessity.

**Comment by fynv** [comment]
I've just commited another patch, now keep tracking of image layout and access mask.
Texture2D::download() was also having a "oldLayout=VK_IMAGE_LAYOUT_UNDEFINED" issue.

**Comment by aschrein** [comment]
Now it works thanks! Closing the PR.

**Pull request closed without merging**
